apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: resource-event-source
spec:
  template:
    serviceAccountName: serviceAccount
  resource:
    example:
      namespace: argo-events
      filter:
        # prefix: argo-events-job
        labels:
          - key: workflows.argoproj.io/completed
            operation: ==
            value: 'true'
        createdBy: null
      group: argoproj.io
      version: v1alpha1
      resource: workflows
      eventTypes:
        - ADD